version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: shortenurls
      DB_USERNAME: testuser
      DB_PASSWORD: testpass123
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: shortenurls
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
