[phases.setup]
nixPkgs = ["php81", "mysql", "curl"]

[phases.install]
cmds = [
  # โหลด composer แล้ว install ทันที ไม่ mv แล้ว
  "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" && php composer-setup.php && php composer.phar install --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT}"

