[phases.setup]
nixPkgs = ["php81", "mysql", "curl"]

[phases.install]
cmds = [
  "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"",
  "php composer-setup.php",
  "mv composer.phar /usr/local/bin/composer",
  "composer install --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8000"
